# Generated by Django 3.2.6 on 2021-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='USERID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='CUSTOMER NAME')),
                ('customer_callnumber', models.CharField(max_length=13, verbose_name='CUSTOMER CALLNUMBER')),
                ('customer_reservation', models.BooleanField(verbose_name='CUSTOMER RESERVATION')),
                ('customer_reservation_restaurant', models.CharField(max_length=20, verbose_name='CUSTOMER RESERVATION RESTAURANT')),
                ('customer_reservation_date', models.DateField(verbose_name='CUSTOMER RESERVATION DATE')),
                ('customer_reservation_time', models.TimeField(verbose_name='CUSTOMER RESERVATION TIME')),
            ],
            options={
                'db_table': 'restaurant_reservations',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='USERID')),
                ('restaurant_name', models.CharField(max_length=20, verbose_name='RESTAURANT NAME')),
                ('restaurant_description', models.CharField(max_length=100, verbose_name='RESTAURANT DESCRIPTION')),
                ('restaurant_callnumber', models.CharField(max_length=13, verbose_name='RESTAURANT CALLNUMBER')),
                ('restaurant_address', models.CharField(max_length=100, verbose_name='RESTAURANT ADDRESS')),
                ('reservation_possible_date', models.DateField(verbose_name='RESTAURANT POSSIBLE DATE')),
                ('reservation_time_bigin', models.TimeField(verbose_name='RESTAURANT TIME BEGIN')),
                ('reservation_time_end', models.TimeField(verbose_name='RESTAURANT TIME END')),
                ('reservation_seat', models.IntegerField(verbose_name='RESTAURANT SEAT')),
            ],
            options={
                'db_table': 'restaurant_reservation',
            },
        ),
    ]
