# Generated by Django 3.2.6 on 2021-08-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_reservations',
        ),
        migrations.AlterModelTable(
            name='post',
            table='restaurant_reservations',
        ),
    ]
