# Generated by Django 3.2.6 on 2021-08-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reservation_time_bigin',
            new_name='reservation_time_begin',
        ),
    ]
