# Generated by Django 3.2.6 on 2021-08-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_reservation_time_bigin_post_reservation_time_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_callnumber',
            field=models.CharField(max_length=13, verbose_name='고객 전화번호'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=20, verbose_name='고객 이름'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation',
            field=models.BooleanField(verbose_name='예약 여부'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation_date',
            field=models.DateField(verbose_name='예약한 날짜'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation_restaurant',
            field=models.CharField(max_length=20, verbose_name='예약한 식당'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation_time',
            field=models.TimeField(verbose_name='예약한 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reservation_possible_date',
            field=models.DateField(verbose_name='영업 요일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reservation_seat',
            field=models.IntegerField(verbose_name='예약 가능 좌석 수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reservation_time_begin',
            field=models.TimeField(verbose_name='영업 시작하는 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reservation_time_end',
            field=models.TimeField(verbose_name='영업 끝나는 시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_address',
            field=models.CharField(max_length=100, verbose_name='가게 주소'),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_callnumber',
            field=models.CharField(max_length=13, verbose_name='가게 전화번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_description',
            field=models.CharField(max_length=100, verbose_name='가게 설명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_name',
            field=models.CharField(max_length=20, verbose_name='우리 가게 이름'),
        ),
    ]
