# Generated by Django 3.2.6 on 2021-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_customer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation_date',
            field=models.DateField(verbose_name='예약 날짜'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation_restaurant',
            field=models.CharField(max_length=20, verbose_name='예약 식당'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_reservation_time',
            field=models.TimeField(verbose_name='예약 시간'),
        ),
    ]
